// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmicether/ethstate/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QuerySlotDataRequest struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Slot            string `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (m *QuerySlotDataRequest) Reset()         { *m = QuerySlotDataRequest{} }
func (m *QuerySlotDataRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySlotDataRequest) ProtoMessage()    {}
func (*QuerySlotDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{0}
}
func (m *QuerySlotDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySlotDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySlotDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySlotDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySlotDataRequest.Merge(m, src)
}
func (m *QuerySlotDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySlotDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySlotDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySlotDataRequest proto.InternalMessageInfo

func (m *QuerySlotDataRequest) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *QuerySlotDataRequest) GetSlot() string {
	if m != nil {
		return m.Slot
	}
	return ""
}

type QuerySlotDataRequestResponse struct {
	SlotData *SlotData `protobuf:"bytes,1,opt,name=slot_data,json=slotData,proto3" json:"slot_data,omitempty"`
}

func (m *QuerySlotDataRequestResponse) Reset()         { *m = QuerySlotDataRequestResponse{} }
func (m *QuerySlotDataRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySlotDataRequestResponse) ProtoMessage()    {}
func (*QuerySlotDataRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{1}
}
func (m *QuerySlotDataRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySlotDataRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySlotDataRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySlotDataRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySlotDataRequestResponse.Merge(m, src)
}
func (m *QuerySlotDataRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySlotDataRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySlotDataRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySlotDataRequestResponse proto.InternalMessageInfo

func (m *QuerySlotDataRequestResponse) GetSlotData() *SlotData {
	if m != nil {
		return m.SlotData
	}
	return nil
}

type QueryContractDataRequest struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *QueryContractDataRequest) Reset()         { *m = QueryContractDataRequest{} }
func (m *QueryContractDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContractDataRequest) ProtoMessage()    {}
func (*QueryContractDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{2}
}
func (m *QueryContractDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractDataRequest.Merge(m, src)
}
func (m *QueryContractDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractDataRequest proto.InternalMessageInfo

func (m *QueryContractDataRequest) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type QueryContractDataRequestResponse struct {
	Slots []SlotData `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots"`
}

func (m *QueryContractDataRequestResponse) Reset()         { *m = QueryContractDataRequestResponse{} }
func (m *QueryContractDataRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContractDataRequestResponse) ProtoMessage()    {}
func (*QueryContractDataRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{3}
}
func (m *QueryContractDataRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractDataRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractDataRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractDataRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractDataRequestResponse.Merge(m, src)
}
func (m *QueryContractDataRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractDataRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractDataRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractDataRequestResponse proto.InternalMessageInfo

func (m *QueryContractDataRequestResponse) GetSlots() []SlotData {
	if m != nil {
		return m.Slots
	}
	return nil
}

type QueryEthBlockRequest struct {
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *QueryEthBlockRequest) Reset()         { *m = QueryEthBlockRequest{} }
func (m *QueryEthBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEthBlockRequest) ProtoMessage()    {}
func (*QueryEthBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{4}
}
func (m *QueryEthBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEthBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEthBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEthBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEthBlockRequest.Merge(m, src)
}
func (m *QueryEthBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEthBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEthBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEthBlockRequest proto.InternalMessageInfo

func (m *QueryEthBlockRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type QueryEthBlockRequestResponse struct {
	BlockData *BlockData `protobuf:"bytes,1,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
}

func (m *QueryEthBlockRequestResponse) Reset()         { *m = QueryEthBlockRequestResponse{} }
func (m *QueryEthBlockRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEthBlockRequestResponse) ProtoMessage()    {}
func (*QueryEthBlockRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae737d3be7943e, []int{5}
}
func (m *QueryEthBlockRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEthBlockRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEthBlockRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEthBlockRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEthBlockRequestResponse.Merge(m, src)
}
func (m *QueryEthBlockRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEthBlockRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEthBlockRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEthBlockRequestResponse proto.InternalMessageInfo

func (m *QueryEthBlockRequestResponse) GetBlockData() *BlockData {
	if m != nil {
		return m.BlockData
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySlotDataRequest)(nil), "cosmicether.ethstate.v1.QuerySlotDataRequest")
	proto.RegisterType((*QuerySlotDataRequestResponse)(nil), "cosmicether.ethstate.v1.QuerySlotDataRequestResponse")
	proto.RegisterType((*QueryContractDataRequest)(nil), "cosmicether.ethstate.v1.QueryContractDataRequest")
	proto.RegisterType((*QueryContractDataRequestResponse)(nil), "cosmicether.ethstate.v1.QueryContractDataRequestResponse")
	proto.RegisterType((*QueryEthBlockRequest)(nil), "cosmicether.ethstate.v1.QueryEthBlockRequest")
	proto.RegisterType((*QueryEthBlockRequestResponse)(nil), "cosmicether.ethstate.v1.QueryEthBlockRequestResponse")
}

func init() {
	proto.RegisterFile("cosmicether/ethstate/v1/query.proto", fileDescriptor_27ae737d3be7943e)
}

var fileDescriptor_27ae737d3be7943e = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xd6, 0x54, 0x92, 0x69, 0x41, 0x19, 0x0a, 0x86, 0x50, 0xd6, 0x3a, 0x05, 0xd1, 0x83,
	0x3b, 0x24, 0xa5, 0x87, 0x45, 0xa9, 0x34, 0xb6, 0xe0, 0xc1, 0x8b, 0x2b, 0x5e, 0xbc, 0x2c, 0xb3,
	0x9b, 0x61, 0x77, 0x35, 0xdd, 0x49, 0x77, 0x5e, 0x8a, 0x25, 0xe4, 0xe2, 0x2f, 0x10, 0xfc, 0x19,
	0x5e, 0x3c, 0x79, 0xf5, 0xda, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0xc4, 0x1f, 0x22, 0x33, 0xd9, 0xdd,
	0xae, 0x21, 0xd3, 0x5a, 0x6f, 0x6f, 0xdf, 0x7c, 0xef, 0x7b, 0xdf, 0xf7, 0xde, 0x63, 0xd1, 0x76,
	0x28, 0xe4, 0x51, 0x12, 0x72, 0x88, 0x79, 0x46, 0x39, 0xc4, 0x12, 0x18, 0x70, 0x7a, 0xd2, 0xa1,
	0xc7, 0x23, 0x9e, 0x9d, 0x3a, 0xc3, 0x4c, 0x80, 0xc0, 0x77, 0x2a, 0x20, 0xa7, 0x00, 0x39, 0x27,
	0x9d, 0xf6, 0x7d, 0x53, 0x75, 0x09, 0xd2, 0x04, 0xed, 0x8d, 0x48, 0x44, 0x42, 0x87, 0x54, 0x45,
	0x79, 0x76, 0x33, 0x12, 0x22, 0x1a, 0x70, 0xca, 0x86, 0x09, 0x65, 0x69, 0x2a, 0x80, 0x41, 0x22,
	0x52, 0x39, 0x7f, 0x25, 0xaf, 0xd1, 0xc6, 0x4b, 0xa5, 0xe1, 0xd5, 0x40, 0xc0, 0x01, 0x03, 0xe6,
	0xf1, 0xe3, 0x11, 0x97, 0x80, 0x1f, 0xa2, 0xdb, 0xa1, 0x48, 0x21, 0x63, 0x21, 0xf8, 0xac, 0xdf,
	0xcf, 0xb8, 0x94, 0x2d, 0x6b, 0xcb, 0x7a, 0xd0, 0xf4, 0x6e, 0x15, 0xf9, 0xfd, 0x79, 0x1a, 0x63,
	0x54, 0x97, 0x03, 0x01, 0xad, 0x15, 0xfd, 0xac, 0x63, 0xe2, 0xa3, 0xcd, 0x65, 0xb4, 0x1e, 0x97,
	0x43, 0x91, 0x4a, 0x8e, 0x9f, 0xa2, 0xa6, 0xc2, 0xf9, 0x7d, 0x06, 0x4c, 0xf3, 0xae, 0x75, 0x89,
	0x63, 0xf0, 0xef, 0x94, 0x48, 0xaf, 0x21, 0x73, 0x3e, 0x72, 0x88, 0x5a, 0xba, 0xc1, 0xb3, 0x5c,
	0xcc, 0xff, 0x69, 0x27, 0x01, 0xda, 0x32, 0xd1, 0x94, 0x5a, 0xf7, 0xd0, 0xaa, 0x6a, 0xab, 0x38,
	0x6e, 0xfc, 0x9b, 0xce, 0x5e, 0xfd, 0xec, 0xe7, 0xdd, 0x9a, 0x37, 0x2f, 0x23, 0x6e, 0x3e, 0xe2,
	0x43, 0x88, 0x7b, 0x03, 0x11, 0xbe, 0x2b, 0x64, 0xde, 0x43, 0xeb, 0x81, 0xfa, 0xf6, 0x63, 0x9e,
	0x44, 0x31, 0x68, 0x89, 0x75, 0x6f, 0x4d, 0xe7, 0x9e, 0xeb, 0x14, 0x09, 0xf2, 0x31, 0x2e, 0x94,
	0x96, 0xd2, 0x7a, 0x08, 0xcd, 0x29, 0x2a, 0x73, 0xdc, 0x36, 0xea, 0xbb, 0x80, 0x7a, 0x4d, 0x1d,
	0x2b, 0xb7, 0xdd, 0x2f, 0x75, 0xb4, 0xaa, 0x9b, 0xe0, 0xaf, 0x16, 0x6a, 0x14, 0x0b, 0xc3, 0x8f,
	0x8c, 0x34, 0xcb, 0x16, 0xdb, 0xde, 0xbd, 0x16, 0xbc, 0x30, 0x40, 0x0e, 0x3e, 0x7c, 0xff, 0xfd,
	0x69, 0x65, 0x0f, 0x3f, 0xa1, 0xa6, 0x1b, 0x2f, 0x87, 0x4a, 0xc7, 0x8b, 0x4b, 0x9d, 0xd0, 0xb1,
	0x7a, 0x9d, 0xe0, 0x6f, 0x16, 0x5a, 0xaf, 0x6e, 0x10, 0x77, 0x2e, 0x57, 0xb3, 0x64, 0xdb, 0x6d,
	0xf7, 0xda, 0x25, 0xa5, 0x89, 0x7d, 0x6d, 0xe2, 0x31, 0x76, 0x8d, 0x26, 0x4a, 0xe5, 0x06, 0x23,
	0xf8, 0xb3, 0x85, 0x1a, 0xc5, 0x92, 0xaf, 0x1a, 0xfd, 0xc2, 0x31, 0x5c, 0x35, 0x7a, 0xc3, 0xed,
	0x10, 0x57, 0xab, 0xde, 0xc1, 0x1d, 0x7a, 0xc9, 0xef, 0xc5, 0xd7, 0x77, 0x42, 0xc7, 0xd5, 0x43,
	0x9d, 0xf4, 0x5e, 0x9c, 0x4d, 0x6d, 0xeb, 0x7c, 0x6a, 0x5b, 0xbf, 0xa6, 0xb6, 0xf5, 0x71, 0x66,
	0xd7, 0xce, 0x67, 0x76, 0xed, 0xc7, 0xcc, 0xae, 0xbd, 0xe9, 0x46, 0x09, 0xc4, 0xa3, 0xc0, 0x09,
	0xc5, 0x11, 0x65, 0x6f, 0x59, 0x2a, 0x59, 0x96, 0xb8, 0xbb, 0x7f, 0x75, 0x78, 0x7f, 0xd1, 0x03,
	0x4e, 0x87, 0x5c, 0x06, 0x37, 0xf5, 0x9f, 0x68, 0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x87, 0x2c, 0x78, 0x25, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	SlotData(ctx context.Context, in *QuerySlotDataRequest, opts ...grpc.CallOption) (*QuerySlotDataRequestResponse, error)
	ContractData(ctx context.Context, in *QueryContractDataRequest, opts ...grpc.CallOption) (*QueryContractDataRequestResponse, error)
	EthBlock(ctx context.Context, in *QueryEthBlockRequest, opts ...grpc.CallOption) (*QueryEthBlockRequestResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SlotData(ctx context.Context, in *QuerySlotDataRequest, opts ...grpc.CallOption) (*QuerySlotDataRequestResponse, error) {
	out := new(QuerySlotDataRequestResponse)
	err := c.cc.Invoke(ctx, "/cosmicether.ethstate.v1.Query/SlotData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ContractData(ctx context.Context, in *QueryContractDataRequest, opts ...grpc.CallOption) (*QueryContractDataRequestResponse, error) {
	out := new(QueryContractDataRequestResponse)
	err := c.cc.Invoke(ctx, "/cosmicether.ethstate.v1.Query/ContractData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EthBlock(ctx context.Context, in *QueryEthBlockRequest, opts ...grpc.CallOption) (*QueryEthBlockRequestResponse, error) {
	out := new(QueryEthBlockRequestResponse)
	err := c.cc.Invoke(ctx, "/cosmicether.ethstate.v1.Query/EthBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	SlotData(context.Context, *QuerySlotDataRequest) (*QuerySlotDataRequestResponse, error)
	ContractData(context.Context, *QueryContractDataRequest) (*QueryContractDataRequestResponse, error)
	EthBlock(context.Context, *QueryEthBlockRequest) (*QueryEthBlockRequestResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SlotData(ctx context.Context, req *QuerySlotDataRequest) (*QuerySlotDataRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlotData not implemented")
}
func (*UnimplementedQueryServer) ContractData(ctx context.Context, req *QueryContractDataRequest) (*QueryContractDataRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractData not implemented")
}
func (*UnimplementedQueryServer) EthBlock(ctx context.Context, req *QueryEthBlockRequest) (*QueryEthBlockRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EthBlock not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SlotData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySlotDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SlotData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmicether.ethstate.v1.Query/SlotData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SlotData(ctx, req.(*QuerySlotDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ContractData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryContractDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmicether.ethstate.v1.Query/ContractData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractData(ctx, req.(*QueryContractDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EthBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEthBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EthBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmicether.ethstate.v1.Query/EthBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EthBlock(ctx, req.(*QueryEthBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmicether.ethstate.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SlotData",
			Handler:    _Query_SlotData_Handler,
		},
		{
			MethodName: "ContractData",
			Handler:    _Query_ContractData_Handler,
		},
		{
			MethodName: "EthBlock",
			Handler:    _Query_EthBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmicether/ethstate/v1/query.proto",
}

func (m *QuerySlotDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySlotDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySlotDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Slot) > 0 {
		i -= len(m.Slot)
		copy(dAtA[i:], m.Slot)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Slot)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySlotDataRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySlotDataRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySlotDataRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlotData != nil {
		{
			size, err := m.SlotData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryContractDataRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractDataRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractDataRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Slots) > 0 {
		for iNdEx := len(m.Slots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Slots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEthBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEthBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEthBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEthBlockRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEthBlockRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEthBlockRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockData != nil {
		{
			size, err := m.BlockData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySlotDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Slot)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySlotDataRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotData != nil {
		l = m.SlotData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContractDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContractDataRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Slots) > 0 {
		for _, e := range m.Slots {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEthBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	return n
}

func (m *QueryEthBlockRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockData != nil {
		l = m.BlockData.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySlotDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySlotDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySlotDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySlotDataRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySlotDataRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySlotDataRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SlotData == nil {
				m.SlotData = &SlotData{}
			}
			if err := m.SlotData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractDataRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractDataRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractDataRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slots = append(m.Slots, SlotData{})
			if err := m.Slots[len(m.Slots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEthBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEthBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEthBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEthBlockRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEthBlockRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEthBlockRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockData == nil {
				m.BlockData = &BlockData{}
			}
			if err := m.BlockData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
