// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmicether/ethquery/v1/ethquery.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EthQuery struct {
	Id         string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	QueryType  string                                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	Request    []byte                                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	CallbackId string                                 `protobuf:"bytes,4,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	Height     github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=height,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"height"`
}

func (m *EthQuery) Reset()         { *m = EthQuery{} }
func (m *EthQuery) String() string { return proto.CompactTextString(m) }
func (*EthQuery) ProtoMessage()    {}
func (*EthQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f1d1bb5fc15bcf, []int{0}
}
func (m *EthQuery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EthQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EthQuery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EthQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthQuery.Merge(m, src)
}
func (m *EthQuery) XXX_Size() int {
	return m.Size()
}
func (m *EthQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_EthQuery.DiscardUnknown(m)
}

var xxx_messageInfo_EthQuery proto.InternalMessageInfo

func (m *EthQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EthQuery) GetQueryType() string {
	if m != nil {
		return m.QueryType
	}
	return ""
}

func (m *EthQuery) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *EthQuery) GetCallbackId() string {
	if m != nil {
		return m.CallbackId
	}
	return ""
}

func init() {
	proto.RegisterType((*EthQuery)(nil), "cosmicether.ethquery.v1.EthQuery")
}

func init() {
	proto.RegisterFile("cosmicether/ethquery/v1/ethquery.proto", fileDescriptor_37f1d1bb5fc15bcf)
}

var fileDescriptor_37f1d1bb5fc15bcf = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xce, 0x2f, 0xce,
	0xcd, 0x4c, 0x4e, 0x2d, 0xc9, 0x48, 0x2d, 0xd2, 0x4f, 0x2d, 0xc9, 0x28, 0x2c, 0x4d, 0x2d, 0xaa,
	0xd4, 0x2f, 0x33, 0x84, 0xb3, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4, 0x91, 0xd4, 0xe9,
	0xc1, 0xe5, 0xca, 0x0c, 0xa5, 0x24, 0x41, 0x12, 0xf9, 0xc5, 0xf1, 0x60, 0x65, 0xfa, 0x10, 0x0e,
	0x44, 0x8f, 0x94, 0x48, 0x7a, 0x7e, 0x7a, 0x3e, 0x44, 0x1c, 0xc4, 0x82, 0x88, 0x2a, 0x9d, 0x62,
	0xe4, 0xe2, 0x70, 0x2d, 0xc9, 0x08, 0x04, 0x19, 0x20, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0x22, 0x24, 0xcb, 0xc5, 0x05, 0x36, 0x39, 0xbe,
	0xa4, 0xb2, 0x20, 0x55, 0x82, 0x09, 0x2c, 0xce, 0x09, 0x16, 0x09, 0xa9, 0x2c, 0x48, 0x15, 0x92,
	0xe0, 0x62, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x09,
	0x82, 0x71, 0x85, 0xe4, 0xb9, 0xb8, 0x93, 0x13, 0x73, 0x72, 0x92, 0x12, 0x93, 0xb3, 0xe3, 0x33,
	0x53, 0x24, 0x58, 0xc0, 0x3a, 0xb9, 0x60, 0x42, 0x9e, 0x29, 0x42, 0x21, 0x5c, 0x6c, 0x19, 0xa9,
	0x99, 0xe9, 0x19, 0x25, 0x12, 0xac, 0x20, 0x39, 0x27, 0x9b, 0x13, 0xf7, 0xe4, 0x19, 0x6e, 0xdd,
	0x93, 0x57, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0x85, 0xba, 0x1e, 0x4a,
	0xe9, 0x16, 0xa7, 0x64, 0xeb, 0x83, 0x9c, 0x51, 0xac, 0xe7, 0x99, 0x57, 0x72, 0x69, 0x8b, 0x2e,
	0x17, 0xd4, 0x73, 0x9e, 0x79, 0x25, 0x41, 0x50, 0xb3, 0x9c, 0x7c, 0x4e, 0x3c, 0x92, 0x63, 0xbc,
	0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63,
	0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x08, 0xc9, 0xdc, 0xc4, 0xac, 0xc4, 0xbc, 0xe2, 0xc4, 0xa2,
	0x4c, 0x4b, 0x53, 0x7d, 0xe4, 0xe0, 0xae, 0x40, 0x04, 0x38, 0xd8, 0x9e, 0x24, 0x36, 0x70, 0x08,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x07, 0x70, 0x7a, 0x47, 0x95, 0x01, 0x00, 0x00,
}

func (m *EthQuery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EthQuery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EthQuery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Height.Size()
		i -= size
		if _, err := m.Height.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthquery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.CallbackId) > 0 {
		i -= len(m.CallbackId)
		copy(dAtA[i:], m.CallbackId)
		i = encodeVarintEthquery(dAtA, i, uint64(len(m.CallbackId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Request) > 0 {
		i -= len(m.Request)
		copy(dAtA[i:], m.Request)
		i = encodeVarintEthquery(dAtA, i, uint64(len(m.Request)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.QueryType) > 0 {
		i -= len(m.QueryType)
		copy(dAtA[i:], m.QueryType)
		i = encodeVarintEthquery(dAtA, i, uint64(len(m.QueryType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintEthquery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEthquery(dAtA []byte, offset int, v uint64) int {
	offset -= sovEthquery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EthQuery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovEthquery(uint64(l))
	}
	l = len(m.QueryType)
	if l > 0 {
		n += 1 + l + sovEthquery(uint64(l))
	}
	l = len(m.Request)
	if l > 0 {
		n += 1 + l + sovEthquery(uint64(l))
	}
	l = len(m.CallbackId)
	if l > 0 {
		n += 1 + l + sovEthquery(uint64(l))
	}
	l = m.Height.Size()
	n += 1 + l + sovEthquery(uint64(l))
	return n
}

func sovEthquery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEthquery(x uint64) (n int) {
	return sovEthquery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EthQuery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthquery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EthQuery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EthQuery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthquery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthquery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthquery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthquery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEthquery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEthquery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Request = append(m.Request[:0], dAtA[iNdEx:postIndex]...)
			if m.Request == nil {
				m.Request = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthquery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthquery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallbackId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthquery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthquery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthquery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEthquery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEthquery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEthquery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthquery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEthquery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEthquery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEthquery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEthquery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEthquery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEthquery = fmt.Errorf("proto: unexpected end of group")
)
